name: Export Check

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
      - name: Install dependencies
        run: npm install
      - name: Build and Export
        run: npm run export
      - name: Verify Export
        run: ls -la extensions/dist
