name: Export Check

on:
  push:
    branches:
      - feature/*
      - develop

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/setup-node@v4
        with:
          node-version: 22.2.0
      - name: Install dependencies
        run: npm install
      - name: Build and Export
        run: npm run export
      - name: Verify Export
        run: ls -la extensions/dist
